config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from oz_m_de.common.views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('oz_m_de.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^organizations/', include('oz_m_de.organizations.urls', namespace='organizations')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

oz_m_de/organizations/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.OrganizationListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^create/$',
        view=views.OrganizationCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^(?P<pk>[1-9]+)/$',
        view=views.OrganizationDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^delete/(?P<pk>[1-9]+)',
        view=views.OrganizationDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^update/(?P<pk>[1-9]+)/$',
        view=views.OrganizationUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^opening-hours/(?P<pk>[1-9]+)/$',
        view=views.OrganizationOpeningHoursView.as_view(),
        name='opening-hours'
    ),
    url(
        regex=r'^rooms-available/(?P<pk>[1-9]+)/$',
        view=views.rooms_available,
        name='rooms-available'
    )
]

oz_m_de/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

oz_m_de/common/models.py
from django.db import models

# Create your models here.

oz_m_de/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

oz_m_de/common/views.py
from django.utils import timezone
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404

from oz_m_de.organizations.models import Organization, OrganizationCategory


def getkey(item: OrganizationCategory) -> str:
    return item.name


class HomePageView(TemplateView):
    template_name = "pages/home.html"

    def get(self, request, *args, **kwargs):
        category_id = request.GET.get("category")
        category = None
        if category_id:
            category = get_object_or_404(OrganizationCategory, pk=category_id)
            organizations = Organization.objects.is_active_and_category(category)
            categories = None
        else:
            organizations = None
            categories = OrganizationCategory.objects.has_active_organizations()

        day = timezone.now().strftime("%a").lower

        ctx = {
            "category": category,
            "organizations": organizations,
            "day": day,
            "organization_types": categories
        }

        return self.render_to_response(ctx)

oz_m_de/organizations/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import http
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, TemplateView, DeleteView

from .forms import (OrganizationForm, AddressForm, OpeningHoursForm, DAYS,
                    OrganizationAdminForm)
from .models import Organization, DayOpeningHours
from common.memberships import is_organizations_admin


class OrganizationCreateView(LoginRequiredMixin, TemplateView):
    template_name = "organizations/organization_form.html"

    def get_context_data(self, **kwargs):
        super(OrganizationCreateView, self).get_context_data(**kwargs)
        data = kwargs.get("data")
        context = {
            "organization_form": OrganizationForm(data=data),
            "address_form": AddressForm(data=data),
            "form_action": "create",
            "title": "Create organization"
        }

        return context

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data()
        return self.render_to_response(ctx)

    def post(self, request, *args, **kwargs):
        organization_form = OrganizationForm(data=request.POST)
        address_form = AddressForm(data=request.POST)

        if organization_form.is_valid() and address_form.is_valid():
            return self.forms_valid(organization_form, address_form)
        return self.forms_invalid(request.POST)

    def forms_valid(self, organization_form, address_form):
        organization = organization_form.save(commit=False)
        organization.owner = self.request.user

        organization.save()

        address = address_form.save(commit=False)
        address.country = "DE"
        address.organization = organization
        address.save()

        return redirect("organizations:list")

    def forms_invalid(self, data):
        ctx = self.get_context_data(data=data)
        return self.render_to_response(ctx)


class OrganizationUpdateView(LoginRequiredMixin, TemplateView):
    template_name = "organizations/organization_form.html"

    def check_user(self, organization: Organization):
        user = self.request.user
        if is_organizations_admin(user):
            return
        if not organization.owner == user:
            raise PermissionDenied()

    def get_organization(self, pk):
        try:
            organization = Organization.objects.get(pk=pk)
            address = organization.addresses.first()
        except ObjectDoesNotExist:
            raise http.Http404()

        self.check_user(organization)

        return organization, address

    def get_organization_form(self, organization, data):
        user = self.request.user
        if is_organizations_admin(user):
            return OrganizationAdminForm(data=data, instance=organization)
        return OrganizationForm(data=data, instance=organization)

    def get_context_data(self, **kwargs):
        super(OrganizationUpdateView, self).get_context_data(**kwargs)

        pk = kwargs.get("pk")
        data = kwargs.get("data")

        organization, address = None, None

        if pk:
            organization, address = self.get_organization(pk)

        context = {
            "organization_form": self.get_organization_form(organization, data),
            "address_form": AddressForm(data=data, instance=address),
            "form_action": "update",
            "title": "Update organization",
            "pk": pk,
            "is_active": organization.is_active,
            "is_blocked": organization.is_blocked,
            "is_approved": organization.is_approved
        }

        if is_organizations_admin(self.request.user):
            context["owner_email"] = organization.owner.email

        return context

    def get(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        ctx = self.get_context_data(pk=pk)
        return self.render_to_response(ctx)

    def post(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        organization, address = self.get_organization(pk)
        organization_form = self.get_organization_form(organization, request.POST)
        address_form = AddressForm(data=request.POST, instance=address)

        if address_form.is_valid() and organization_form.is_valid():
            return self.is_valid(organization_form, address_form, pk)
        return self.is_invalid(request.POST)

    def is_valid(self, organization_form, address_form, pk):
        organization_form.save()
        address_form.save()

        ctx = self.get_context_data(pk=pk)
        return self.render_to_response(ctx)

    def is_invalid(self, data):
        ctx = self.get_context_data(data=data)
        return self.render_to_response(ctx)


class OrganizationDetailView(LoginRequiredMixin, DetailView):
    model = Organization
    # These next two lines tell the view to index lookups by username
    slug_field = 'pk'
    slug_url_kwarg = 'pk'


class OrganizationListView(LoginRequiredMixin, ListView):
    model = Organization

    def get_queryset(self):
        user = self.request.user

        if is_organizations_admin(user):
            return Organization.objects.sorted_by_order()
        return Organization.objects.sorted_by_name_for_owner(user)

    def get_context_data(self, **kwargs):
        context = super(OrganizationListView, self).get_context_data(**kwargs)
        context["is_organization_admin"] = is_organizations_admin(self.request.user)
        return context


class OrganizationDeleteView(LoginRequiredMixin, DeleteView):
    model = Organization
    success_url = reverse_lazy("organizations:list")

    template_name = "organizations/organization_delete.html"


class OrganizationOpeningHoursView(LoginRequiredMixin, TemplateView):
    template_name = "organizations/organization_opening_hours.html"

    def get(self, request, *args, **kwargs):
        organization_pk = kwargs.get("pk")
        organization = Organization.objects.get(pk=organization_pk)

        ctx = {"pk": organization_pk}

        if organization.update_opening_hours_daily:
            if organization.today:
                instance = organization.today
            else:
                instance = DayOpeningHours()
                instance.save()
                organization.today = instance
                organization.save()
            ctx["today_form"] = OpeningHoursForm(day="Today", instance=instance)

        else:
            for day, name in DAYS.items():
                if getattr(organization, day):
                    instance = getattr(organization, day)
                else:
                    instance = DayOpeningHours()
                    instance.save()
                    setattr(organization, day, instance)
                    organization.save()
                ctx["{}_form".format(day)] = OpeningHoursForm(prefix=day, instance=instance, day=name)
        return self.render_to_response(ctx)

    def post(self, request, *args, **kwargs):
        organization_pk = kwargs.get("pk")
        organization = Organization.objects.get(pk=organization_pk)

        forms = {}

        if organization.update_opening_hours_daily:
            instance = organization.today
            forms["today_form"] = OpeningHoursForm(day="Today", data=request.POST, instance=instance)
        else:
            for day, name in DAYS.items():
                instance = getattr(organization, day)
                forms["{}_form".format(day)] = OpeningHoursForm(day=name, data=request.POST,
                                                                instance=instance, prefix=day)

        for form in forms.values():
            if not form.is_valid():
                return self.is_invalid(forms, organization_pk)
        return self.is_valid(forms, organization_pk, organization)

    def is_valid(self, forms, organization_pk, organization):
        for form in forms.values():
            form.save()
        forms["pk"] = organization_pk
        return self.render_to_response(forms)

    def is_invalid(self, forms, organization_pk):
        forms["pk"] = organization_pk
        return self.render_to_response(forms)


def rooms_available(request, *args, **kwargs):
    pk = kwargs.get("pk")

    organization = Organization.objects.get(pk=pk)
    organization.rooms_available = not organization.rooms_available
    organization.save()

    return redirect(reverse_lazy("organizations:list"))

oz_m_de/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

oz_m_de/templates/organizations/organization_delete.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Delete Organization" %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h2>{% trans "Delete Organization" %}</h2>
            <form action="{% url "organizations:delete" organization.pk %}" method="post">
                {% csrf_token %}
                <p>{% trans "Are you sure you want to delete " %}{{ organization.name }}?</p>
                <a role="button" class="btn btn-default" href="{% url "organizations:list" %}">{% trans "Cancel" %}</a>
                <input type="submit" name="submit" value="{% trans "Yes, delete this organization" %}" class="btn btn-primary btn-submit" id="submit-id-submit"/>
            </form>
        </div>
    </div>
{% endblock content %}

oz_m_de/templates/organizations/organization_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}{% trans "Organization"%}: {{ object.name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">
      <h2>{{ object.name }}</h2>
    </div>
  </div>


</div>
{% endblock content %}

oz_m_de/templates/organizations/organization_form.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ title }}</h2>
            {% if form_action == "update" %}
                {% if is_blocked %}
                    <div class="alert alert-danger">
                        {% trans "This organization is currently blocked and will not be displayed on the website" %}
                    </div>
                    {% elif not is_approved %}
                    <div class="alert alert-info">{% trans "This organization has not been approved yet.
                        At soon as it is approved, it will be shown displayed the website" %}</div>
                    {% elif not is_active %}
                    <div class="alert alert-warning">
                        {% trans "This organization is currently not active and is not displayed on the website." %}
                    </div>
                {% else %}
                    <div class="alert alert-success">{% trans "This organization is displayed on the website" %}</div>
                {% endif %}
                {% if owner_email %}
                    <div>{% trans "Email" %}: {{ owner_email }}</div>
                {% endif %}
                <form action="{% url "organizations:update" pk %}" class="uniForm" method="post">
            {% elif form_action == "create" %}
                <form action="{% url "organizations:create" %}" class="uniForm" method="post">
            {% endif %}
            {% csrf_token %}
            {% crispy organization_form %}
            {% crispy address_form %}
            <a role="button" class="btn btn-default" href="{% url "organizations:list" %}">{% trans "Cancel" %}</a>
            <input type="submit" name="submit" value="Submit" class="btn btn-primary btn-submit" id="submit-id-submit"/>
            </form>
        </div>
    </div>
{% endblock content %}

oz_m_de/templates/organizations/organization_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}{% trans "Organizations" %}{% endblock %}

{% block content %}
    <h2>{% trans "Organizations" %}</h2>
    <a class="btn btn-primary" href="{% url 'organizations:create' %}" role="button">{% trans "Create organization" %}</a>
    <hr/>
    <div class="list-group">
        {% for organization in organization_list %}
            <div class="list-group-item">
                <div class="col-md-12">
                    <div class="col-md-4"><h4 class="list-group-item-heading">{{ organization.name }}</h4></div>
                    <div class="col-md-5"><h4 class="list-group-item-heading">| {{ organization.category }}</h4></div>
                    {% if is_organization_admin %}
                        <div class="col-md-2">Order: {{ organization.order }}</div>
                    {% endif %}
                </div>


                <a href="{% url "organizations:update" organization.id %}"
                   class="btn btn-primary btn-submit">{% trans "Update" %}</a>
                <a href="{% url "organizations:opening-hours" organization.id %}"
                   class="btn btn-primary btn-submit">{% trans "Opening hours" %}</a>
                <a href="{% url "organizations:delete" organization.id %}"
                   class="btn btn-primary btn-submit">{% trans "Delete" %} </a>
                {% if organization.category.rooms_available_applies %}
                    {% if organization.rooms_available %}
                        <a href="{% url "organizations:rooms-available" organization.id %}"
                           class="btn btn-success btn-submit">{% trans "Set to No rooms available" %}</a>
                    {% else %}
                        <a href="{% url "organizations:rooms-available" organization.id %}"
                           class="btn btn-warning btn-submit">{% trans "Set to rooms available" %}</a>
                    {% endif %}
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock content %}

oz_m_de/templates/organizations/organization_opening_hours.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Opening hours" %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h2>{% trans "Opening hours" %}</h2>
            <form action="{% url "organizations:opening-hours" pk %}" class="uniForm" method="post">
               <p>{% trans "Use a colon (:) as a separator between hours and minutes" %}</p>

                {% csrf_token %}
                {% if today_form %}
                    {% crispy today_form %}
                {% else %}
                    {% crispy mon_form %}
                    {% crispy tue_form %}
                    {% crispy wed_form %}
                    {% crispy thu_form %}
                    {% crispy fri_form %}
                    {% crispy sat_form %}
                    {% crispy sun_form %}
                {% endif %}
                <a role="button" class="btn btn-default" href="{% url "organizations:list" %}">{% trans "Cancel" %}</a>
                <input type="submit" name="submit" value="{% trans "Save" %}" class="btn btn-primary btn-submit"
                       id="submit-id-submit"/>
            </form>
        </div>
    </div>
{% endblock content %}